

package com.example.hrms.mernis;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.0.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 576BC6EDF2717A518E1B10AC72E4F0ADA1AD0BB6DBBECBC6122D56446221D6C6C9F5FC31EAA653DB8574F1E24F81B252189D274640B51CB856A52A3AEFB58BCD
//------------------------------------------------------------------------

public class SVMBinaryObject implements java.io.Serializable
{
    private byte[] _bytes = null;    
    private transient java.io.InputStream _stream = null;

    private String _contentType = null;

    public SVMBinaryObject(byte[] bytes) {
        _bytes = bytes;
    }

    public SVMBinaryObject(java.io.InputStream stream) {
        _stream = stream;
    }
    
    public Object getUnderlayingObject()
    {
        if (_bytes != null)
            return _bytes;
        else if (_stream != null)
            return _stream;
        else 
            return null;
    }
    
    public java.io.InputStream getStream()
    {
        return _stream;
    }
    
    public byte[] getBytes() {
        return _bytes;
    }

    public void setBytes(byte[] bytes) {
        this._bytes = bytes;
    }

    public String getContentType() {
        return _contentType;
    }

    public void setContentType(String contentType) {
        this._contentType = contentType;
    }
}