
package com.example.hrms.mernis;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.0.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 576BC6EDF2717A518E1B10AC72E4F0ADA1AD0BB6DBBECBC6122D56446221D6C6C9F5FC31EAA653DB8574F1E24F81B252189D274640B51CB856A52A3AEFB58BCD
//------------------------------------------------------------------------
import java.net.URL;
import java.io.*;
import java.net.HttpURLConnection;
import java.util.HashMap;
import java.util.Map;
import java.util.List;

public interface SVMConnectionProvider
{
    SVMResponseData sendRequest(String url,String requestBody,HashMap< String,String> httpHeaders, SVMRequestResultHandler handler) throws java.lang.Exception;
}

class SVMHttpConnectionProvider implements SVMConnectionProvider{

    public void prepareRequest(HttpURLConnection url,String requestBody, SVMRequestResultHandler handler) throws java.lang.Exception {
        OutputStreamWriter wr = new OutputStreamWriter(url.getOutputStream());
        wr.write(requestBody);
        wr.flush();
    }

    @Override
    public SVMResponseData sendRequest(String url,String requestBody, HashMap< String, String> httpHeaders,SVMRequestResultHandler handler ) throws java.lang.Exception
    {
        URL urlObject=new URL(url);
        HttpURLConnection connection=(HttpURLConnection)urlObject.openConnection();
        connection.setRequestMethod("POST");
        connection.setDoOutput(true);
        for(Map.Entry<String, String> entry : httpHeaders.entrySet())
        {
            connection.setRequestProperty(entry.getKey(),entry.getValue());
        }

        prepareRequest(connection,requestBody,handler);


        SVMResponseData response=new SVMResponseData();
        for(Map.Entry<String, List<String>> entry : connection.getHeaderFields().entrySet())
        {
            if(entry.getKey()!=null)
            {
                String values = "";
                for (String value : entry.getValue()) {
                    values = values + value;
                }
                response.getHeaders().put(entry.getKey(),values);
            }
        }
        
        try(InputStream dataStream = getResponseStream(connection,response,handler))
        {
            response.setBody(SVMHelper.streamToString(dataStream));
        }
        
        return response;
    }

    protected InputStream getResponseStream(
        HttpURLConnection url,
        SVMResponseData response,
        SVMRequestResultHandler handler
    ) throws java.lang.Exception
    {
        try{
            return url.getInputStream();
        }
        catch (IOException ex)
        {
            return url.getErrorStream();
        }
    }
}