

package com.example.hrms.mernis;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.0.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 576BC6EDF2717A518E1B10AC72E4F0ADA1AD0BB6DBBECBC6122D56446221D6C6C9F5FC31EAA653DB8574F1E24F81B252189D274640B51CB856A52A3AEFB58BCD
//------------------------------------------------------------------------

public class SVMSoapException extends java.lang.Exception
{
    private org.w3c.dom.Element _details=null;
    private Object _fault = null;
    
    public SVMSoapException(String message,org.w3c.dom.Element details)
    {
        super(message);
        _details=details;
    }

    public SVMSoapException(Object fault)
    {
        _fault=fault;
    }

    public Object getFault() {
        return _fault;
    }


    public org.w3c.dom.Element getDetails() {
        return _details;
    }
}